### ISSUE TITLE
No space in shell for through hole resistor

### ISSUE THREAD

**Issue by the0remora** [jeffqchen/Extron-Audio-3.5mm-Adapter#1]
I am currently running a test print to confirm this but there was a void left for the 3.5mm jack but I don't see one where the legs would be for a through hole. If it is an issue can you provide the source of the STL? I am willing to fix it and send it back

**Comment by jeffqchen** [comment]
> I am currently running a test print to confirm this but there was a void left for the 3.5mm jack but I don't see one where the legs would be for a through hole. If it is an issue can you provide the source of the STL? I am willing to fix it and send it back

That was so that you could use either an SMD or a through hole. Do not populate both of them as that will be an issue.

If the legs of the through hole resistors would be a problem, you might wanna trim the legs then solder them from the top side to make sure the bottom is flat.

**Comment by the0remora** [comment]
If they are trimmed flush after soldier with minimal solder it's not an issue. I hase started trimming them before soldering and that works well. Closing this by saying these to print well in resin.
